name: VALIDAÇÃO DE MERGE

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  validate-merge:
    name: Validação de Merge
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar ambiente Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.7'
          cache: true

      - name: Instalar dependências
        run: flutter pub get

      - name: Verificar formatação do código
        run: flutter format --set-exit-if-changed .

      - name: Analisar código com Dart Analysis
        run: flutter analyze

      # - name: Rodar testes unitários
      #   run: flutter test
